models/Query.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "query".
 *
 * @property int $id
 * @property int $user_id
 * @property string $query
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Mesh[] $meshes
 * @property User $user
 */
class Query extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'query';
    }
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className()
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'query'], 'required'],
            [['user_id', 'created_at', 'updated_at'], 'integer'],
            [['query'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'query' => 'Query',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeshes()
    {
        return $this->hasMany(Mesh::className(), ['query_id' => 'id']);
    }

    public function getCountMeshes()
    {
        return $mashes = Mesh::find()->where(['query_id' => $this->id])->count();

    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\BaseModel;
use app\models\forms\Login;
use app\models\forms\Signup;
use app\models\Mesh;
use app\models\Pmids;
use app\models\Query;
use app\models\User;
use PubMed\Article;
use PubMed\PubMedId;
use PubMed\Term;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\forms\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionTest()
    {
        $base = new BaseModel();
        $api = new Term();
        $search = Yii::$app->request->get('search');
        $articles = $api->query($search);
        $allArticles = $base->getArray($articles);
        debug($allArticles,1);
        die();
        //return $articles;
    }

    /** Stage One
     * Displays homepage.
     *
     * @return string
     */

    public function actionIndex()
    {
        // Add to SESSION
        Yii::$app->session->open();
        $session = Yii::$app->session;
        $search = '';
        $base = new BaseModel();
        $allArticles = [];
        if (!Yii::$app->user->isGuest) {
            $id = Yii::$app->user->getId();
            $user = User::find()->where(['id' => $id])->one();
            $this->view->params['username'] = $user->username;
        }

        if (Yii::$app->request->get('search')) {
            $search = Yii::$app->request->get('search');
            $amount = Yii::$app->request->get('amount');
            $page = Yii::$app->request->get('page');
            if (($page > 1) || ($session['search'] == $search && ($session['amount'] == $amount) && $session['deleted'] === false)) {
                $allArticles = $session['query'];
            } else {
                $api = new Term();
                if (empty($amount)) {
                    $amount = 10;
                }

                $session['deleted'] = false;
                $api->setReturnMax($amount); // set max returned articles, defaults to 10
                $articles = $api->query($search);

                // Create array
                $allArticles = $base->getArray($articles);
                if (!empty($session['query'])) {
                    $c = count($allArticles);
                    if ($session['count']) {
                        $c = $session['count'];
                    }
                    $session->destroy();
                    $session->set('count', $c);
                    $session->set('amount', $amount);
                }
                $session->set('amount', $amount);
                $session->set('query', $allArticles);
                $session->set('search', $search);
            }
        }

        $sort = Yii::$app->request->get('sort');
        $sortFirst = 'sortDesc';
        if ($sort) {
            $allArticles = $base->sortPmids($allArticles, $sort);
            $sortFirst = $sort === 'sortDesc' ? 'sortAsc' : 'sortDesc';
        }

        // Pagination
        $pagination = $base->pagination(Yii::$app->request->get(), $allArticles);
        $allArticles = array_slice($allArticles, $pagination['offset'], $pagination['limit']);

        return $this->render('index', [
            'articles' => $allArticles,
            'totalPages' => $pagination['totalPages'],
            'limit' => $pagination['limit'],
            'page' => $pagination['page'],
            'search' => $search,
            'amount' => $session['amount'],
            'count' => $pagination['total'],
            'allCount' => $session['count'] ? $session['count'] : '',
            'sortFirst' => $sortFirst
        ]);
    }


    /** Check amounts of Articles
     * @return bool|int|mixed
     */
    public function actionCountCheck()
    {
        $base = new BaseModel();
        $session = Yii::$app->session;
        if (Yii::$app->request->get('search')) {
            $search = Yii::$app->request->get('search');
            $api = new Term();
            $api->setReturnMax(1); // set max returned articles
            $articles = $api->query($search);
            // Create array
            $allArticles = $base->getArray($articles);
            $c = count($allArticles);
            if ($session['count']) {
                $c = $session['count'];
            }
            return $c;
        }
        return false;
    }

    /** Stage One
     * @param $id
     * @return string
     */
    public function actionDelete($id = null)
    {
        $session = Yii::$app->session;
        $base = new BaseModel();
        $search = $session['search'];
        $articles = $session['query'];
        $ids = Yii::$app->request->get('delIds');
        $session['deleted'] = true;
        if ($id == 0) {
            unset($articles[0]);
        }
        if (!empty($id)) {
            unset($articles[$id]);
        }
        if (!empty($ids)) {
            foreach ($ids as $id) {
                if ($id == 0) {
                    unset($articles[0]);
                }
                unset($articles[$id]);
            }
        }

        Yii::$app->session['query'] = array_values($articles);
        $articles = Yii::$app->session['query'];
        $sort = Yii::$app->request->get('sort');
        $sortFirst = 'sortDesc';
        $sortFirstID = 'sortDesc';
        if ($sort) {
            $articles = $base->sortPmids($articles, $sort);
            $sortFirst = $sort === 'sortDesc' ? 'sortAsc' : 'sortDesc';
        }
        $pagination = $base->pagination(Yii::$app->request->get(), $articles);

        $allArticles = array_slice($articles, $pagination['offset'], $pagination['limit']);
        if (empty($allArticles) && ($pagination['offset'] - $pagination['limit']) >= 0) {
            $allArticles = array_slice($articles, $pagination['offset'] - $pagination['limit'], $pagination['limit']);
        }

        if (!Yii::$app->user->isGuest) {
            $id = Yii::$app->user->getId();
            $user = User::find()->where(['id' => $id])->one();
            $this->view->params['username'] = $user->username;
        }

        return $this->renderAjax('indexAjax', [
            'articles' => $allArticles,
            'totalPages' => $pagination['totalPages'],
            'limit' => $pagination['limit'],
            'page' => $pagination['page'],
            'search' => $search,
            'count' => $pagination['total'],
            'amount' => $session['amount'],
            'allCount' => $session['count'] ? $session['count'] : '',
            'sortFirst' => $sortFirst,
            'sortFirstID' => $sortFirstID
        ]);

    }


    /** Stage Two
     * Article's Meshes
     * @return string
     */
    public function actionMesh()
    {
        $allArticles = [];
        $session = Yii::$app->session;
        $base = new BaseModel();
        $search = $session['search'];
        $ids = Yii::$app->request->get('delIds');
        if ($session['query']) {
            if ($ids) {
                foreach ($session['query'] as $key => $article) {
                    $meshs = $article['meshs'];
                    if ($meshs && in_array($key, $ids)) {
                        $allArticles[] = $article;
                    }
                }

            } else {
                foreach ($session['query'] as $article) {
                    $meshs = $article['meshs'];
                    if ($meshs) {
                        $allArticles[] = $article;
                    }
                }
            }
        }
        if (!empty($allArticles)) {
            $session['query'] = $allArticles;
        }
        $sort = Yii::$app->request->get('sort');
        $sortFirst = 'sortDesc';
        if ($sort) {
            $allArticles = $base->sortMesh($allArticles, $sort);
            $sortFirst = $sort === 'sortDesc' ? 'sortAsc' : 'sortDesc';
        }
        $sortId = Yii::$app->request->get('sortID');
        $sortFirstID = 'sortDesc';
        if ($sortId) {
            $allArticles = $base->sortPmids($allArticles, $sortId);
            $sortFirstID = $sortId === 'sortDesc' ? 'sortAsc' : 'sortDesc';
        }
        if (!Yii::$app->user->isGuest) {
            $id = Yii::$app->user->getId();
            $user = User::find()->where(['id' => $id])->one();
            $this->view->params['username'] = $user->username;
        }
        $pagination = $base->pagination(Yii::$app->request->get(), $allArticles);
        $allArticles = array_slice($allArticles, $pagination['offset'], $pagination['limit']);

        return $this->render('mesh', [
            'articles' => $allArticles,
            'totalPages' => $pagination['totalPages'],
            'limit' => $pagination['limit'],
            'page' => $pagination['page'],
            'search' => $search,
            'count' => $pagination['total'],
            'sortFirst' => $sortFirst,
            'sortFirstID' => $sortFirstID
        ]);
    }


    /** Stage Three
     * @return string
     */

views/site/cabinet.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 12.12.2018
 * Time: 23:15
 */

use yii\helpers\Url;
$this->title = 'Кабинет';
?>

<div class="page-header header-filter" data-parallax="true" filter-color="rose"
     style="background-image: url('/images/bg2.jpg');">
</div>

<div class="section section-gray">
    <div class="container">
        <div class="main main-raised main-product" style="min-height: 500px">
            <?php if (!empty($querys)): ?>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Search Words</th>
                            <th>Result</th>
                            <th>Date</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if (!empty($querys)): ?>
                            <?php foreach ($querys as $k => $item): ?>
                                <tr>
                                    <th><?= $k+1 ?></th>
                                    <td><?= $item->query ?></td>
                                    <td><?= $item->countMeshes ?></td>
                                    <th><?= date('d.m.Y H:i',$item->created_at) ?></th>
                                    <th><a class="btn btn-primary" href="<?= Url::to(['/site/user-mesh','id' => $item->id]) ?>">View</a></th>

                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        </tbody>
                    </table>
                </div>

            <?php else: ?>
                <h3>Сохраненных результатов нет</h3>
            <?php endif; ?>

            <?php if(Yii::$app->session->get('save')):?>
                <?php $this->registerJs('swal("Успешно", "Ваш поиск успешно сохранено", "success");');
                    Yii::$app->session->destroy();
                 ?>

            <?php endif; ?>
        </div>
    </div>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
//$this->layout = 'main';
?>
<div class="page-header header-filter" data-parallax="true" filter-color="rose"
     style="background-image: url('/images/bg2.jpg');">
</div>

<div class="section section-gray">
    <div class="container">
        <div class="main main-raised main-product text-center" style="min-height: 500px">
            <h1>Ошибка 4 0 4</h1>
            <h3>Страница не найдена</h3>
            <a href="/" class="btn btn-primary">Вернуться на главную страницу</a>
        </div>
    </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Главная';
?>

<div class="page-header header-filter" data-parallax="true" filter-color="rose"
     style="background-image: url('/images/bg2.jpg');">
    <?php if (!empty($articles)): ?>
        <div class="container">
            <div class="row title-row">
                <div class="col-md-2" style="display: flex">
                    <a href="<?= Url::to(['/']) ?>" class="btn btn-white pull-right"><i
                                class="material-icons">keyboard_backspace</i> Назад к поиску</a>
                </div>
                <div class="col-md-4 col-md-offset-6">
                    <button class="btn btn-white pull-right">Найдено
                        результатов: <?= !empty($allCount) ? $allCount : '' ?> <?= '(из них запрошено ' . $count . ' )' ?></button>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
<div class="section section-gray">
    <div class="container">
        <div class="main main-raised main-product" style="min-height: 600px">
            <?php if (empty($articles)): ?>
                <div class="text-center">

                    <h2 class="title">Some Text</h2>
                    <p class="description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, ad assumenda at
                        consequuntur, cupiditate dignissimos esse labore minus nesciunt obcaecati odio officiis
                        pariatur, perferendis temporibus vel. Ipsum iusto nihil soluta.
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab, ad assumenda at
                        consequuntur, cupiditate dignissimos esse labore minus nesciunt obcaecati odio officiis
                        pariatur, perferendis temporibus vel. Ipsum iusto nihil soluta.</p>
                    <?php if (!empty($search)): ?>
                        <p class="text-primary" style="margin-top: 20px">По вашему запросу "<?= $search ?>" ничего не
                            найдено. Попробуйте другой вопрос</p>
                    <?php endif; ?>
                    <div class="card card-form-horizontal" style="margin-top: 50px">
                        <div class="card-content">
                            <div class="row">
                                <div class="col-sm-10">
                                    <div class="input-group">
	        											<span class="input-group-addon">
	        												<i class="material-icons">search</i>
	        											</span>
                                        <div class="form-group is-empty first-search-input">
                                            <input type="text" id="firstSearch" placeholder="Введите слово"
                                                   class="form-control" required>
                                            <span class="material-input"></span>
                                        </div>
                                    </div>
                                    <p class="description">Введите слово или список слов через запятую (Jhon, Jhon
                                        Lennon)</p>
                                </div>
                                <div class="col-sm-2">
                                    <button type="submit" class="btn btn-primary btn-block btn-search">Искать
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            <?php else: ?>
                <div class="row">
                    <div class="col-md-4"><h4>Результат поиска: <?= Yii::$app->request->get('search') ?></h4></div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <label style="width: 60%; float: left; padding-top: 10px">
                            На одной странице:
                        </label>
                        <div style="float: right; width: 30%; margin-top: -10px">
                            <select class="selectpicker select-limit" data-search="<?= $search ?>"
                                    data-style="select-with-transition" data-amount="<?= $amount ?>"
                                    title="<?= $limit ?>" data-size="7" tabindex="-98">
                                <option value="100">100</option>
                                <option value="200">200</option>
                                <option value="300">300</option>
                                <option value="<?= $count ?>">Показать все</option>

                            </select>
                        </div>

                    </div>
                </div>


                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="all" value="" class="checkAll">
                                    </label>
                                </div>
                            </th>
                            <th>PMID <a href="<?= Url::current(['sort' => $sortFirst ])?>"><i class="material-icons text-muted">sort</i></a></th>
                            <th style="width: 70%">Заголовок</th>
                            <th style="width: 10%;"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <form action="<?= Url::to(['/site/delete']) ?>" id="search-form"  class="search-index-ajax">
                            <?php foreach ($articles as $k => $article): ?>
                                <tr>
                                    <td class="text-center"><?= $k + (($page - 1) * $limit) + 1 ?></td>
                                    <td>
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="delIds[]"
                                                       value="<?= $k + (($page - 1) * $limit) ?>"
                                                       class="articleCheckbox">
                                            </label>
                                        </div>
                                    </td>
                                    <td><?= $article['pmid'] ?></td>
                                    <td>
                                        <a href="http://ncbi.nlm.nih.gov/pubmed/<?= $article['pmid'] ?>"
                                            data-toggle="tooltip" data-placement="bottom" title="" data-container="body" data-original-title="<?= $article['content'] ?>"><?= $article['title'] ?></a>
                                        <p style="font-size: 12px">
                                            <?= $article['journal'] ? $article['journal'] . '. ' : '' ?>
                                            <?= $article['date'] ? $article['date'] . ', ' : '' ?>
                                            <?= $article['pii'] ? 'pii: ' . $article['pii'] . ' ' : '' ?>
                                            <?= $article['doi'] ? 'doi: ' . $article['doi'] . ' ' : '' ?>
                                        </p>
                                    </td>
                                    <td>
                                        <a href="#"
                                           data-url="<?= Url::to(['/site/delete'])?>"
                                           data-id="<?= $k + (($page - 1) * $limit) ?>"
                                           data-limit="<?= $limit ?>"
                                           data-page="<?= $page ?>"
                                           class="btn btn-danger btn-simple index-delete">
                                            Удалить
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>

                        </tbody>
                    </table>
                    <div class="table-pagination">
                        <ul class="pagination pagination-info">
                            <?php if ($totalPages != 0 && $totalPages > 1): ?>
                                <?php for ($i = 1; $i <= $totalPages; $i++): ?>
                                    <li class="<?= $page == $i ? 'active' : '' ?>">
                                        <a href="<?= Url::to(['/', 'search' => $search, 'page' => $i, 'limit' => $limit,'amount' => $amount]) ?>"><?= $i ?></a>
                                    </li>
                                <?php endfor; ?>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <input type="hidden" name="limit" value="<?= $limit ?>">
                    <input type="hidden" name="page" value="<?= $page ?>">
                    <button class="btn btn-danger btn-delete-ajax" type="button">Удалить PMID</button>
                    <button type="button" class="btn btn-primary goSelected">Получить mesh только по выбранным</button>
                    <a href="<?= Url::to(['/site/mesh']) ?>" class="btn btn-primary">Получить все mesh</a>
                    </form>
                    <button class="btn btn-info" data-toggle="modal" data-target="#downloadQ" style="float: right">Скачать CSV</button>

                </div>
            <?php endif; ?>
        </div>
    </div>
</div>


<div class="modal fade" id="mySearchModel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     style="">
    <div class="modal-dialog modal-signup">
        <div class="modal-content">
            <div class="card card-signup card-plain">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        <i class="material-icons">clear</i>
                    </button>
                    <h4 class="modal-title">Поиск</h4>
                </div>
                <div class="modal-body">
                    <h4 id="textPoisk" style="text-align: center;text-transform: uppercase;"></h4>
                    <form method="get" action="<?= Url::to(['/site/index']) ?>" id="indexSearch">
                        <div class="row">
                            <input type="hidden" name="search" id="searchM" placeholder="Введите слово"
                                   class="form-control">
                            <div class="col-sm-2">
                                <div class="input-group" style="text-align: right; width:100%;">
                                    <div class="form-group is-empty">
                                        <h4 style="text-transform: uppercase;">Запросить</h4>
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="input-group" style="width:100%;">
                                    <input type="text" name="amount" placeholder="Кол-во результатов" id="amountModal"
                                           class="form-control" required>
                                    <span class="material-input"></span>

                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="input-group" style="width:100%; margin-top: 12px">
                                    <button type="submit" class="btn btn-primary btn-block">Искать</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--// Download Model-->
<div class="modal fade" id="downloadQ" tabindex="-1" role="dialog" aria-labelledby="downloadQ" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="material-icons">clear</i>
                </button>
                <h4 class="modal-title">ВЫБЕРИТЕ ТИП ДАННЫХ ДЛЯ ЭКСПОРОТА</h4>
            </div>
            <div class="modal-body">
                <form style="margin: 20px">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="pmidExport" checked="">
                            PMID
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="abstExport" checked="">
                            ЗАГОЛОВКИ И АБСТРАКТЫ
                        </label>
                    </div>
                </form>
                <button class="btn btn-info downloadQuery">Скачать CSV</button>
            </div>

        </div>
    </div>
</div>

views/site/pmids-ajax.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 17.01.2019
 * Time: 1:29
 */
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
        <i class="material-icons">clear</i>
    </button>
    <h4 class="modal-title">Mesh: <?= $article['mesh'] ?></h4>
</div>
<div class="modal-body">
    <p><?= $article['pmids'] ?></p>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Закрыть</button>
</div>

views/site/table-ajax.php
<?php
/**
 * Created by PhpStorm.
 * User: SoS
 * Date: 12.12.2018
 * Time: 0:56
 */
?>